/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawalRouteImport } from './routes/withdrawal'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MonteCarloRouteImport } from './routes/monte-carlo'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as InputsRouteImport } from './routes/inputs'
import { Route as DataRouteImport } from './routes/data'
import { Route as IndexRouteImport } from './routes/index'

const WithdrawalRoute = WithdrawalRouteImport.update({
  id: '/withdrawal',
  path: '/withdrawal',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MonteCarloRoute = MonteCarloRouteImport.update({
  id: '/monte-carlo',
  path: '/monte-carlo',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const InputsRoute = InputsRouteImport.update({
  id: '/inputs',
  path: '/inputs',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/inputs': typeof InputsRoute
  '/insights': typeof InsightsRoute
  '/monte-carlo': typeof MonteCarloRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/risk': typeof RiskRoute
  '/scenarios': typeof ScenariosRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/withdrawal': typeof WithdrawalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/inputs': typeof InputsRoute
  '/insights': typeof InsightsRoute
  '/monte-carlo': typeof MonteCarloRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/risk': typeof RiskRoute
  '/scenarios': typeof ScenariosRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/withdrawal': typeof WithdrawalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/inputs': typeof InputsRoute
  '/insights': typeof InsightsRoute
  '/monte-carlo': typeof MonteCarloRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/risk': typeof RiskRoute
  '/scenarios': typeof ScenariosRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/withdrawal': typeof WithdrawalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data'
    | '/inputs'
    | '/insights'
    | '/monte-carlo'
    | '/portfolio'
    | '/profile'
    | '/risk'
    | '/scenarios'
    | '/settings'
    | '/timeline'
    | '/withdrawal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data'
    | '/inputs'
    | '/insights'
    | '/monte-carlo'
    | '/portfolio'
    | '/profile'
    | '/risk'
    | '/scenarios'
    | '/settings'
    | '/timeline'
    | '/withdrawal'
  id:
    | '__root__'
    | '/'
    | '/data'
    | '/inputs'
    | '/insights'
    | '/monte-carlo'
    | '/portfolio'
    | '/profile'
    | '/risk'
    | '/scenarios'
    | '/settings'
    | '/timeline'
    | '/withdrawal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataRoute: typeof DataRoute
  InputsRoute: typeof InputsRoute
  InsightsRoute: typeof InsightsRoute
  MonteCarloRoute: typeof MonteCarloRoute
  PortfolioRoute: typeof PortfolioRoute
  ProfileRoute: typeof ProfileRoute
  RiskRoute: typeof RiskRoute
  ScenariosRoute: typeof ScenariosRoute
  SettingsRoute: typeof SettingsRoute
  TimelineRoute: typeof TimelineRoute
  WithdrawalRoute: typeof WithdrawalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdrawal': {
      id: '/withdrawal'
      path: '/withdrawal'
      fullPath: '/withdrawal'
      preLoaderRoute: typeof WithdrawalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monte-carlo': {
      id: '/monte-carlo'
      path: '/monte-carlo'
      fullPath: '/monte-carlo'
      preLoaderRoute: typeof MonteCarloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inputs': {
      id: '/inputs'
      path: '/inputs'
      fullPath: '/inputs'
      preLoaderRoute: typeof InputsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataRoute: DataRoute,
  InputsRoute: InputsRoute,
  InsightsRoute: InsightsRoute,
  MonteCarloRoute: MonteCarloRoute,
  PortfolioRoute: PortfolioRoute,
  ProfileRoute: ProfileRoute,
  RiskRoute: RiskRoute,
  ScenariosRoute: ScenariosRoute,
  SettingsRoute: SettingsRoute,
  TimelineRoute: TimelineRoute,
  WithdrawalRoute: WithdrawalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
